#!/usr/bin/env python3
"""Generate the small, fully synthetic media fixture bundled with RelicScope.

The output is deliberately an abstract calibration object, not a real artwork,
collector photograph, museum record, or training sample.  Pillow draws every
pixel and ffmpeg encodes the already-generated frames into a browser-playable
MP4.  Generation is optional: fresh clones include the finished fixture.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, PngImagePlugin


CANVAS = 768
FRAME_COUNT = 6
PROVENANCE = "DEMO/SYNTHETIC — generated by scripts/generate-demo-media.py"


def _font(size: int) -> ImageFont.ImageFont:
    candidates = (
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/Library/Fonts/Arial Bold.ttf",
    )
    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


def _vessel_points(cx: float, phase: float) -> list[tuple[float, float]]:
    profile = (
        (155, 70), (196, 88), (209, 126), (184, 164), (163, 225),
        (154, 330), (180, 445), (215, 545), (208, 598), (166, 624),
    )
    left = [(cx - width + math.sin(phase + y / 75) * 5, y) for width, y in profile]
    right = [(2 * cx - x, y) for x, y in reversed(left)]
    return left + right


def _draw_fixture(phase: float, comparison: bool = False) -> Image.Image:
    image = Image.new("RGB", (CANVAS, CANVAS), (235, 231, 220))
    draw = ImageDraw.Draw(image)

    # Instrument-style backdrop and scale marks keep the fixture visually rich
    # enough to exercise quality gates while avoiding a real object depiction.
    for x in range(0, CANVAS, 32):
        tone = 218 if x % 128 else 198
        draw.line((x, 0, x, CANVAS), fill=(tone, tone, tone - 4), width=1)
    for y in range(0, CANVAS, 32):
        tone = 218 if y % 128 else 198
        draw.line((0, y, CANVAS, y), fill=(tone, tone, tone - 4), width=1)
    draw.rectangle((32, 32, 736, 736), outline=(28, 48, 63), width=5)

    cx = 384 + 9 * math.sin(phase)
    points = _vessel_points(cx, phase)
    draw.polygon(points, fill=(238, 235, 221), outline=(22, 61, 94))
    draw.line(points + [points[0]], fill=(18, 48, 78), width=8, joint="curve")

    # Synthetic blue bands, fiducials and controlled pseudo-crackle.
    for y, width in ((112, 176), (210, 168), (384, 156), (544, 202), (596, 202)):
        shift = int(8 * math.sin(phase + y / 80))
        draw.rounded_rectangle(
            (cx - width + shift, y - 9, cx + width + shift, y + 9),
            radius=8,
            fill=(24, 78, 132),
        )
    for index in range(18):
        angle = phase + index * math.pi / 9
        radius_x = 108 + (index % 3) * 17
        radius_y = 152 + (index % 4) * 23
        x = cx + math.cos(angle) * radius_x
        y = 350 + math.sin(angle) * radius_y
        draw.ellipse((x - 12, y - 12, x + 12, y + 12), fill=(28, 92, 153))
    for index in range(11):
        x0 = int(cx - 118 + index * 23 + 4 * math.sin(phase + index))
        y0 = 250 + (index % 4) * 62
        draw.line(
            (x0, y0, x0 + 15, y0 + 24, x0 - 3, y0 + 52),
            fill=(91, 114, 126),
            width=2,
        )

    # The comparison view has an explicit registration offset, not damage.
    if comparison:
        draw.rectangle((cx + 114, 272, cx + 162, 320), outline=(224, 110, 52), width=6)
        draw.line((cx + 138, 260, cx + 138, 332), fill=(224, 110, 52), width=2)
        draw.line((cx + 102, 296, cx + 174, 296), fill=(224, 110, 52), width=2)

    # Calibration colors and a permanent, visible provenance banner.
    chips = ((35, 67, 91), (42, 105, 165), (216, 112, 60), (223, 190, 85), (231, 231, 220))
    for index, color in enumerate(chips):
        draw.rectangle((64 + index * 54, 662, 108 + index * 54, 706), fill=color, outline=(25, 38, 47), width=2)
    draw.rectangle((0, 0, CANVAS, 78), fill=(15, 31, 43))
    draw.text((28, 15), "DEMO / SYNTHETIC", fill=(91, 228, 193), font=_font(34))
    draw.text((454, 25), "NO REAL ARTIFACT", fill=(245, 240, 223), font=_font(18))
    draw.text((42, 718), "RelicScope calibration fixture · generated pixels", fill=(26, 45, 58), font=_font(17))
    return image


def _save_png(image: Image.Image, path: Path, role: str) -> None:
    metadata = PngImagePlugin.PngInfo()
    metadata.add_text("relicscope.provenance", PROVENANCE)
    metadata.add_text("relicscope.role", role)
    image.save(path, format="PNG", optimize=True, pnginfo=metadata)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_manifests(output: Path, media_paths: list[Path]) -> None:
    relative_paths = sorted(path.relative_to(output) for path in media_paths)
    sums = "".join(f"{_sha256(output / path)}  {path.as_posix()}\n" for path in relative_paths)
    (output / "SHA256SUMS").write_text(sums, encoding="utf-8")
    manifest = {
        "schema": "relicscope.synthetic-media.v1",
        "provenance": "DEMO/SYNTHETIC",
        "contains_real_artifact_media": False,
        "license_scope": "RelicScope demonstration fixture",
        "generation": "scripts/generate-demo-media.py",
        "files": [
            {"path": path.as_posix(), "sha256": _sha256(output / path)}
            for path in relative_paths
        ],
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "demo_media",
    )
    args = parser.parse_args()
    output = args.output.resolve()
    frames_dir = output / "frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    media_paths: list[Path] = []
    reference = output / "reference.png"
    comparison = output / "comparison.png"
    _save_png(_draw_fixture(0.0), reference, "reference")
    _save_png(_draw_fixture(0.22, comparison=True), comparison, "comparison")
    media_paths.extend((reference, comparison))

    for index in range(FRAME_COUNT):
        frame = frames_dir / f"frame_{index + 1:02d}.png"
        _save_png(
            _draw_fixture(index * 2 * math.pi / FRAME_COUNT),
            frame,
            f"video-frame-{index + 1:02d}",
        )
        media_paths.append(frame)

    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise SystemExit("ffmpeg is required only when regenerating synthetic_orbit.mp4")
    video = output / "synthetic_orbit.mp4"
    command = [
        ffmpeg, "-hide_banner", "-loglevel", "error", "-y",
        "-framerate", "2", "-i", str(frames_dir / "frame_%02d.png"),
        "-c:v", "libx264", "-preset", "slow", "-crf", "25",
        "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        "-metadata", "title=RelicScope DEMO/SYNTHETIC fixture",
        "-metadata", "comment=DEMO/SYNTHETIC; no real artifact media",
        "-an", str(video),
    ]
    subprocess.run(command, check=True)
    media_paths.append(video)
    _write_manifests(output, media_paths)
    print(f"Generated {len(media_paths)} synthetic media files in {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
